version: "3"

services:
  db:
    image: mariadb:10.7
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password_root
    env_file:
      - ./db.env

  app:
    image: matomo:fpm-alpine
    restart: always
    links:
      - db
    volumes:
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/applications/apache/ssl/wildcard.sig.rennesmetropole.fr/:/var/applications/apache/ssl/wildcard.sig.rennesmetropole.fr/
    ports:
      - 8090:80
      - 4435:443

volumes:
  db:
  matomo: